<a href="https://colab.research.google.com/github/Ianero22/A_Star/blob/main/A_star.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [68]:
import numpy as np





#def zrekontruuj_trase(przyszedlZ, obecny_wierzcholek):
    #trasa
Cel = np.loadtxt("1.txt", skiprows=1, max_rows=1)

Start= int(Cel[0])
Meta = int(Cel[1])
def zrekonstruuj_trasę(przyszedlZ, obecny_wierzchołek):
        trasa=[obecny_wierzcholek]
        while (przyszedlZ):
            obecny_wierzchołek = przyszedlZ[obecny_wierzchołek]
            trasa.insert(0, obecny_wierzchołek)
        return trasa
def Astar(Start,Meta):
    #Wierzcholki = np.loadtxt("1.txt", max_rows=1)
    Wierzcholki = np.array([[0,0],[0,1],[1,0],[1,1]])
    W = Wierzcholki.shape[0]

    przyszedlZ = np.ones(4)*range(4)
    obecny_wierzcholek = 0
    rozpatrywanie = [Start]
    przejrzane = []

    fx=np.ones([1,W])*10000
    fx[0,Start-1]=int(Start)
    gx=np.ones([1,W])*10000
    gx[0,Start-1]=0
    hx=np.ones([1,W])
    tymczasoweG =np.zeros([1,W+1])*10000

    sciezki = np.loadtxt("1.txt", skiprows=2)
    #print("sciezk",sciezki.shape)
    sasiedzi = sciezki*0
    #print(sasiedzi)
    for i in range(sciezki.shape[0]): # z
        for j in range(sciezki.shape[1]):# do
            if sciezki[i-1,j-1] >0:
              sasiedzi[i-1,j-1]=1

    print("sasiedzi", sasiedzi)
    while rozpatrywanie:
        x = min(rozpatrywanie) #aktualnie rozpatrywany wierzchołek
        print(x)
        if x == Meta:
            return zrekonstruuj_trasę(przyszedlZ, Meta)
        rozpatrywanie.pop()
        przejrzane.append(x)

        for y in range(sasiedzi[x-1].size):
          tymczasoweG[0,y-1] = gx[0,x-1] + sciezki[x-1,y-1]

          if (tymczasoweG[0,y-1] < gx[0,y-1]):
            przyszedlZ[y-1]= x
            gx[0,y-1] = tymczasoweG[0,y-1]
            fx[0,y-1] = gx[0,y-1] + hx[0,y-1]

            #if not rozpatrywanie[]
          #print("gx ", gx[0,x-1]+sciezki[x,y])
          #print("+sciezki[x,y]", sciezki[x,y])

          #
          # print("sasiedzi x",sasiedzi[x-1].size)
          # print("x ", x)
          # print("y", y)
            print("przyszedl z ", przyszedlZ)
          # print("waga", sciezki[x])

    #sciezki = np.array([[0,1,0,1.414],[1,0,1.414,0],[0,1.414,0,1],[1.414,0,1,0]])
    #s = sciezki.size

    print("Start",Start,"\n")
    print("rozpatrywanie",rozpatrywanie,"\n")
    print(Wierzcholki,"\n",Cel,"\n",sciezki)
    print("x ", x)
    print("fx",fx,"\n gx ",gx,"\n hx ",hx, "\n tymczasowe G ", tymczasoweG)

#print("\n sciezka z 1 do 2", sciezki[0,3])

# for j in range(W):
#     for i in range(sciezki[j].shape[0]):

#         if sciezki[j,i]>0:
#             print("wszystkie mozliwe sciezki z ", j+1)
#             print("\n",i+1)



Astar(Start,Meta)

#Astar()

sasiedzi [[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
1
przyszedl z  [0. 1. 2. 1.]
przyszedl z  [0. 1. 2. 1.]
przyszedl z  [0. 1. 1. 1.]
Start 1 

rozpatrywanie [] 

[[0 0]
 [0 1]
 [1 0]
 [1 1]] 
 [1. 4.] 
 [[0.    1.    0.    1.414]
 [1.    0.    1.414 0.   ]
 [0.    1.414 0.    1.   ]
 [1.414 0.    1.    0.   ]]
x  1
fx [[1.    2.    1.    2.414]] 
 gx  [[0.    1.    0.    1.414]] 
 hx  [[1. 1. 1. 1.]] 
 tymczasowe G  [[0.    1.    0.    0.    1.414]]
